Create new workflows for trunk-based dev, deprecate gitflow
IRNAS/irnas-workflows-software pull request #5
Opened 2023-07-10 14:31 UTC by MarkoSagadin

## Description

As the title says.

Closes #4.

## Areas of interest for the reviewer

Check if the added documentation about usage of the CI pipeline is understandable.

Keep it mind that it will be used in the near future by someone that did not use our previous Gitflow development workflow.

## Merging

Once reviewed I will merge the PR myself.

2023-07-10 14:31 UTC, MarkoSagadin commented
Current dependencies on/for this PR:
* dev
  * **PR #5** <a href="https://app.graphite.dev/github/pr/IRNAS/irnas-workflows-software/5" target="_blank"><img src="https://static.graphite.dev/graphite-32x32.png" alt="Graphite" width="10px" height="10px"/></a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/IRNAS/irnas-workflows-software/5?utm_source=stack-comment).

2023-07-11 07:48 UTC, NejcKle requested changes

2023-07-11 07:48 UTC, NejcKle commented on workflow-templates/basic/README.md
> +- checkout `main` branch
missing comma

2023-07-11 07:48 UTC, NejcKle commented on workflow-templates/basic/README.md
> +Workflows `publish-release.yaml` just labels PRs against `main` branch with
Workflow*

2023-07-11 07:52 UTC, NejcKle approved these changes

2023-07-11 07:53 UTC, merged